### ISSUE TITLE
cannot install the latest version freebayes by conda 

### ISSUE THREAD

**Issue by BowenXiao123** [freebayes/freebayes#698] opened 2021-03-24 03:34 UTC
code
`conda install -c bioconda freebayes`
`freebayes --version `
version:  v0.9.21
`conda update -c bioconda freebayes`
`freebayes --version `
version:  v0.9.21

**Comment by jpn2021** [comment] 2021-03-25 22:46
Is there a workaround or a fix?

**Comment by pjotrp** [comment] 2021-04-14 20:34
You need to contact the conda folks.

**Comment by pjotrp** [comment] 2021-04-14 20:37
Duplicate of #694

**Closed by pjotrp** 2021-04-14 20:37 UTC
Labels: please file bugs only - use google groups instead
