### ISSUE TITLE
Exception: Cannot read past the end of the alignment's sequence

### ISSUE THREAD

**Issue by 100kristine** [freebayes/freebayes#58] opened 2013-12-04 21:27 UTC
Hi,

I've been hitting this error on a couple of bam files that I have tried. I attached a screenshot of the area causing the error in igv viewer. Input and error are below. The file already has read groups added. Thank you for any help that you can provide!

Kristine

freebayes -b ../../vcftesting/bamaddrg_LCC23.bam -v ../../vcftesting/freebayes_with_lastexons.vcf -f ../../hg19param/ucsc.hg19.fasta -t ../../hg19param/last_exons.bed 
Exception: Cannot read past the end of the alignment's sequence.
CTTTAAAGATACAAAAAACACGTGTCTTCTGTGGAGCTCTGAGAACAGGACTCCAGCAAAGCACTTTTCAGCCTTGTGGTCTTCAAGCATTTCCAAGATNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCT
GTGACATTGGAAAGAAAAAAAATTAAGACAGATTTGGGTCTCCATGAGCAGAGAGTATTCTTTCCCTTAGTTCTGGGTAGCATAGTGCCCAAGGAAACCTAATCAGTACAGTGGGAAACCAAATCTATTCCAAATCATTACCCATAAGCAATCCTATGGACTCTCTGAGGTTTGACAGAGTCAGCGGCCCTCTCCAATAAATGTGTTTTTCTATAATAATGTGCAGTGTGAGTAATTTGATGTTTTTGACAAATATTTACCCAGCGTTTTATGAAGGAGAAGGTTTGGGGGGCAAGCTGAAGGAGCTCTGACTGCCTTTTGGAGGAGTGTGAGTGGCTTACCTT
chr12:9220338
Abort trap: 6

![screen shot 2013-12-04 at 1 24 43 pm](https://f.cloud.github.com/assets/5431793/1677614/8a8a171c-5d2a-11e3-933b-22f957f065fe.png)

**Comment by holtgrewe** [comment] 2015-03-16 15:12
:+1: I'm getting this problem as well.

**Comment by inti** [comment] 2015-03-23 18:49
I am geeting this as well with spliced RNA-seq alignments

**Comment by visze** [comment] 2015-03-27 13:45
+1

**Comment by ekg** [comment] 2015-03-27 14:15
Would one of you please send me a test case? Ideally something small I
could add to the tests. Sorry for the trouble but this is the easiest way
to resolve things!

**Comment by mjafin** [comment] 2015-03-27 14:18
@ekg I sent you an example file about a year ago (see above). If it went missing can you please contact me and I'll resend it?

**Comment by ekg** [comment] 2015-03-27 14:23
Ah! please resend!

**Comment by mjafin** [comment] 2015-03-27 15:01
@ekg I've just emailed you a 5MB bam file to your bc.edu email address (from my AZ email). Can you please let me know if you're not in receipt of the email in the next few hours. I couldn't reproduce the same exact error with the latest freebayes I'm using but it's probably related (different error output slightly).

**Comment by inti** [comment] 2015-03-27 17:03
Digging a bit more. On my case it was related to spliced alignments produced by HISAT. I do not think the software is an issue but the fact that the cigar string had Ns. I had to use the GATK tool to split reads with Ns on the cigar string and it is now working fine.

I reckon I had this before when working with very small contigs …. 

regards,
Inti

**Comment by inti** [comment] 2015-04-13 18:59
Is this solved? The GATK tool SplitNCigarReads is slow and duplicating a bam file for large projects is not very fun on top of the time to write the file. 

On my case I am calling twice from the bam file, so streaming does not help a great deal since I would need to reformat twice the original bam file to call with freebayes. 

:(

**Comment by inti** [comment] 2015-05-15 14:54
Hi,
This still bugs me ... sorry 

Would it be safe to replace the Ns for a deletion, that is code introns as deletions? 
for example 24S8M**8401N**18M into 24S8M**8401D**18M and then filter out the deletions matching exactly the intro coordinates? Would FreeBayes behave as expected?

@mjafin @visze have you solve this?

**Comment by mjafin** [comment] 2015-05-15 18:27
@inti I've personally given up on anything and everything except VarDict, which happily processes any RNA-seq data I throw at it.

**Comment by inti** [comment] 2015-05-15 19:10
The suggestion above actually seems to work fine, for example using
```
sambamba view -L covereged_regions.bed -h sorted.bam | awk -v OFS='\t' '{{ gsub(/N/,"D", $6); print }}' | sambamba view --format bam -S /dev/stdin | freebayes -f ref_genome.fa --stdin  
```
which will produce variant calls and indels for the introns by knowing which region where covered by the reads, as with `bedtools -bg -split`, that it should be possible to get rid of the intros=indels quite easily. 

I do not see why this would affect the variant calling on bases just next to the exon-intro boundary more than the GATK tool, but I would be great if @ekg could confirm if he thinks the same.

Thanks a lot for pointing me to VarDict, i will have a look right now.

**Comment by travc** [comment] 2015-05-30 22:40
Yep, freebayes is choking on my tophat bams as well... 
RNA-seq friendly freebayes would be a great thing. 

**If you only need SNPs**...

Hacking the bam to change 'N' to 'D' in the CIGAR strings appears to work for me too.

- using @inti suggested `sambamba`+`awk` line took 198 sec (without the `-L covered_regions.bed` part, since I'll deal with that sort of filtering at the vcf level):
```./sambamba view -h F1.bam | awk -v OFS='\t' '{{ gsub(/N/,"D", $6); print }}' | ./sambamba view --format bam -S /dev/stdin > F1_hack1.bam```
- I also tried using `samtools` (v1.0.1) + `awk`, which took 773 sec (`sambamba` really is faster):
```./samtools view -h F1.bam | awk -v OFS='\t' '{{ gsub(/N/,"D", $6); print }}' | ./samtools view -hb - > F1_hack2.bam```
- `splitNreads` from @mjafin is rather slow (still running), but I'm guessing it is a bit more robust.  `calmd` appears to be the bottleneck.
```./samtools view -h F1.bam | ./splitNreads.py | sed 's/RG:A:/RG:Z:/g' | ./samtools calmd -Su - ref.fa 2> /dev/null | ./samtools sort -T _sorted_ -o F1_splitNreads.bam```
(`samtools calmd` produces a lot of warnings, so redirecting them to /dev/null)

This is definitely a hackish workaround since splices will be reported as deletions, but that is OK is some cases (eg: only care about snps).
After filtering with `vcfallelicprimitives`, `vt normalize -r <ref>`, `vcfsnps` it looks fine as far as I can tell.

Note: I've only tried this on a single sample so far, but I'm going to do multisample and will report back if I see any problems.

**Comment by inti** [comment] 2015-06-01 14:51
I have been working with VarDict and it seems to do a good job so far. 
I have been planning a better workaround. What I have in mind is to write a script that changes the N for D on the cigar string, it stores the information on the genomic position of the Ns and then uses this position to filter out the introns called and deletions of the final VCF. I think this would make the approach cleaner in the sense that I reduce the chances of confounding downstream a true deletion with intron marked as a deletion. 

I am not sure when I will get time for this and hopefully soon ... any comments on the idea are welcomed.

**Comment by travc** [comment] 2015-06-01 18:58
@inti ... The difficulty I see is dealing with when  freebayes combines "CIGAR N to D recoded" introns into adjacent variations.  It might be easier to just fixup freebayes itself.

Since freebayes doesn't appear to have any problem handling introns as deletions, maybe it can be made to just treat Ns as Ds except with respect to merging them with other variations.  Introns would then come out as deletions where the CIGAR is all Ns (or N#).  That is trivial to filter and makes conceptual sense to me. 
I've never looked at the freebayes code myself though... so I have no idea how hard it would be to implement.

**Comment by inti** [comment] 2015-06-01 19:28
Yes, a suitable change on the freebayes code would be way better. However, it may be easier to work on filtering out the freebayes output and potentially faster to develop a good practice than tinkering with the freebayes code. I have not looked at it myself and I am not good at C so steep uphills to me to contribute on that. 

Really, my idea was to keep track of the *deletions* in the output of the VCF that are supported by Ns on the original CIGAR strings. It is not much of an insight, I recognise.

**Comment by ekg** [comment] 2015-06-01 19:34
I think this would be a very easy change to freebayes. There is a single
loop in the alleleparser that handles the cigar. Apparently splices aren't
handled correctly... But my problem is that I've not ever worked with
RNAseq data. So I have no way to test.

**Comment by travc** [comment] 2015-06-01 19:51
@ekg  
I'm no RNAseq expert, but here is a little (7kb) example:
https://popi.ucdavis.edu/~travc/tmp/RNAseq_bams_for_freebayes/
There is a bam (extracted from a tophat mapping) and the relevant part of the ref.
I also included a gtf for that little region.

**Comment by peterjc** [comment] 2015-11-05 15:50
Could this issue be retitled to something like "SAM/BAM CIGAR N operator for skipping over introns not supported"?

**Comment by agata-sm** [comment] 2016-02-02 08:54
Hi, I am aware that this is a couple of months old thread, have you found any solution? I have just seen this warning, followed by a core dump when analysing RNA-seq data. I am using version v0.9.21-26-gbfd9832-dirty

**Comment by ekg** [comment] 2016-02-02 08:57
Would you confirm this to be an issue on the current build?

**Comment by agata-sm** [comment] 2016-02-02 09:00
Hey, thanks for the quick reply! I have no idea, haven't used any older version. I can test 0.8.9, 0.9.21, 0.9.4, 0.9.8 (these are installed on the cluster I am using). Depending on the job overload, I should be ready within a few hours.

**Comment by ekg** [comment] 2016-02-02 09:50
I think the problem you are encountering is fixed in a very recent version.
Would you please ask for a recent version to be installed and let me know
if it is resolved?

**Comment by agata-sm** [comment] 2016-02-02 10:32
Thanks! I've requested installation of the newest version, it may take some time though. I will post the result of my test here.

**Comment by colindaven** [comment] 2016-03-30 15:52
The current version  v1.0.2-15-g357f175 seems to be working just fine with RNA-seq BAMs created with the aligner STAR. 

Thanks to all for reporting, discussing and Erik for fixing this.

**Comment by winni2k** [comment] 2020-10-23 09:18
It looks like this issue can be closed?

**Closed** 2020-12-17 18:41 UTC
